### PR TITLE
Win memfs

### PR DESCRIPTION
**Pull request by iainrussell**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Enable MEMFS when building on Windows to avoid problems finding the definitions.

### CODE REVIEW

**Comment by iainrussell** [comment]
@conda-forge-admin, please rerender

**Comment by shahramn** [comment]
> @iainrussell Is [#26 (comment)](https://github.com/conda-forge/eccodes-feedstock/issues/26#issuecomment-278937346) solved? Can we add additional tables/definitions now with `memfs`?

Yes. Even with MEMFS enabled one can still set the environment variables to make ecCodes search for tables/samples in alternative directories

**Comment by kmuehlbauer** [comment]
@shahramn Great! Thanks for the clarification. How much will the binary size increase?

**Comment by shahramn** [comment]
> @shahramn Great! Thanks for the clarification. How much will the binary size increase?

These are the sizes on Linux (release build)
Without MEMFS:
10847016   libeccodes.so

With MEMFS:
10848336  libeccodes.so
25551736  libeccodes_memfs.so

**Comment by iainrussell** [comment]
For reference, *before* this change, on Windows I have these statistics for eccodes 2.21.1 from conda:
```
share dir:          46 MB
eccodes.lib:        289 KB
grib_ls:            129 KB
all grib* binaries: 1.57 MB
all bufr* binaries: 800 KB
```

**Comment by iainrussell** [comment]
For reference, *after* this change, on Windows I have these statistics for eccodes 2.21.1 (build 1) from conda:

```
share dir:          0 MB
eccodes.lib:        289 KB
eccodes_memfs.lib:    3 KB
grib_ls:            129 KB
all grib* binaries: 1.59 MB
all bufr* binaries: 800 KB
```
So, no noticable change in the binaries, and the memfs file is tiny compared to the size of the old share directory!

**Comment by kmuehlbauer** [comment]
@iainrussell That's looking really great. I wonder if this should be done also for the other OS.

**Comment by iainrussell** [comment]
@kmuehlbauer I didn't notice the 22MB dll file that's also installed, but I've updated my previous comment. I'd like some users' experience in using this lib to build with just to make sure it's working ok, but I think we probably will change the other OS builds to use MEMFS as well.

**Comment by kmuehlbauer** [comment]
@iainrussell But still only half in size and legions of files less. I think the other OS will also profit from that change. Thanks for the continuous efforts in improving eccodes.

**Comment by iainrussell** [comment]
Hi @kmuehlbauer , you're very welcome of course! And we couldn't do it without @shahramn doing the developments and others testing it for us! We tested codes_ui, and it works with the new version without having to be rebuilt, so we are fairly confident that other packages should work too.

The rationale behind doing this for Windows was that some users reported problems with eccodes finding the definition files. This should fix that. We have discussed enabling this option for other platforms and need to decide. The downside of MEMFS is that you lose some traceability of the definition files, plus you do not get the sample files. We have the option of installing all these even if MEMFS is enabled, meaning that you get the possible performance boost of MEMFS (not sure how much that is, it will depend a lot on each user's system) and no chance of eccodes not being able to find the tables, but you still have the traceability (pro) and disk usage (con) of having the files there.

**Pull request merged**
