### PR TITLE
Version 2.3.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf CircleCI finished successfully, so this can be merged. Could have have one last look, if everything is OK? I have the version update for the python-eccodes-feedstock ready in my fork to PR it when this is available in the channel.

**Comment by kmuehlbauer** [comment]
> PS: Not that I disabled OS X test in 063f407#r120630581
> 
> Maybe we should try it again with this version.

Yes, we would just need to have some Test-PR.

**Comment by kynan** [comment]
@ocefpaf @kmuehlbauer did you disable the tests on OSX cause they took too long? Or cause they failed? They should be passing! /cc @shahramn

**Comment by kmuehlbauer** [comment]
@kynan,

The eccodes OSX build without tests just fits in the granted travis build time. The final build after this merge needed a restart three times, because it took to long and exceeded travis build time also without tests. As a workaround, we could issue dedicated Test-PRs to check if the tests are running properly. Personally I think there is not much we can do for now.

**Comment by ocefpaf** [comment]
Yep. There isn't much we can do about it.
Hopefully we'll get more Travis-CI time in the future.

**Pull request merged**
