### PR TITLE
Experimental: Add Windows support

### PR DESCRIPTION
**Pull request by dtip**
Hello folks. I've been working with ECMWF to add Windows support for ecCodes. The changes aren't yet released, but are in the ecCodes develop branch, so I'm having a go at getting it to build here.

This is a Work In Progress PR.

The re-render has added a load of .azure-pipelines files due to a change in conda-smithy v3.2.1. Are they desired? I think there's an option somewhere to switch them off.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to 0 (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@dtip Currently `libaec` and `libjasper` are not build for windows. Can those two be dropped for testing this?

**Comment by dtip** [comment]
@kmuehlbauer probably. Lets see!

**Comment by kmuehlbauer** [comment]
> I think eccodes 2.11 is due around the start of Feb. A quick tweak when the tarball is up should get this working.

@dtip No problem! Let's wait for the 2.11 release...

**Comment by kmuehlbauer** [comment]
> But one of the MacOS builds is busted. I'll investigate.

Restarted this particular build. Let's see if it breaks at the same place again.

**Comment by dtip** [comment]
@kmuehlbauer Thanks. It's broken in the same place :(

The conda build process was setting some compiler flags which were breaking the Windows build in (I think) the same place. Perhaps it's a similar problem? The only error message is
`ld: warning: -pie being ignored. It is only used when linking a main executable`
which suggests it could be a flag issue.

**Comment by kmuehlbauer** [comment]
> The conda build process was setting some compiler flags which were breaking the Windows build in (I think) the same place. Perhaps it's a similar problem?

@dtip Can you be a bit more verbose? Which compiler flags did you change?

**Comment by kmuehlbauer** [comment]
We could also try to switch off the log-file limiter to get the whole log or try to conda-build locally (on a mac).

**Comment by dtip** [comment]
> > The conda build process was setting some compiler flags which were breaking the Windows build in (I think) the same place. Perhaps it's a similar problem?
> 
> @dtip Can you be a bit more verbose? Which compiler flags did you change?

These flags were being set and were the only difference between the build on the github/ecmwf/eccodes Windows CI and the conda-forge build:
```
C:\bld\eccodes_1547498513644\work>set "CFLAGS= -MD -GL" 
C:\bld\eccodes_1547498513644\work>set "CXXFLAGS= -MD -GL"
```
The build worked once I cleared the flags before calling `cmake` (https://github.com/conda-forge/eccodes-feedstock/pull/60/commits/1c83f48846a37a3af16bcfec6931885a9b74f67e#diff-d04c86b6bb20341f5f7c53165501a393R4)

**Comment by kmuehlbauer** [comment]
What do you make of this [log message ](https://travis-ci.org/conda-forge/eccodes-feedstock/jobs/479615319#L709)?

Might indicate problems with gfortran on MacOSX, at least for this setup.

**Comment by dtip** [comment]
> What do you make of this [log message ](https://travis-ci.org/conda-forge/eccodes-feedstock/jobs/479615319#L709)?
> 
> Might indicate problems with gfortran on MacOSX, at least for this setup.

It's a red herring I think. The same [error message](https://travis-ci.org/conda-forge/eccodes-feedstock/jobs/463835892#L712) is in older builds which passed!

**Comment by dtip** [comment]
There we go:
`ld: file not found: /usr/lib/system/libsystem_stats.dylib for architecture x86_64`

**Comment by kmuehlbauer** [comment]
@dtip Can you have a look at [this](https://github.com/conda-forge/netcdf-fortran-feedstock/pull/28#issuecomment-448608445) and following comments? It seems, this problem is known and solved.

**Comment by kmuehlbauer** [comment]
@dtip This did the trick :+1: How do we proceed from here? Wait for 2.11 and apply the changes from this test?

**Comment by dtip** [comment]
@kmuehlbauer Thanks for the help! Great find :)

@StephanSiemen What do you think?

We could merge this as-is, which would give us time to mess around with the conda-built binaries ahead of the next ecCodes release. That way if there are any problems which turn up there's a good chance we can get a fix into 2.11. 

Or we could wait. If there are any problems we could always hotfix them. It would avoid us building from GitHub, which is frowned upon.

Either way, once the Windows porting code is in the tarball we should just need to revert 'Windows: get source from git' and it'll be good to go.

**Comment by kmuehlbauer** [comment]
@dtip Thanks for tackling this at ECMWF.

For linux and osx it does not change anything (besides having a rerendering in place). For Windows this would use the current master which might have new features on top of latest 2.10. release. Also we need to fix `libaec` for windows and see how `jasper` is handled there.

So I'm unsure what's the best way to follow up from here.

@conda-forge/eccodes WDYT?

**Comment by StephanSiemen** [comment]
@dtip , @kmuehlbauer,
thank you both for tackling this. Our plan is to start next week with the preparation for the next software release. The Windows changes would be part of this. After that release we could work form the tarballs again as it does now.

**Comment by kmuehlbauer** [comment]
@StephanSiemen Thanks for the heads-up! So my suggestion would be to wait for 2.11. 

We could try to get `libaec` and `jasper` running on windows in due time.

**Comment by kmuehlbauer** [comment]
@dtip Seems that there might be an issue pulling `libarchive` from `defaults (see https://ci.appveyor.com/project/conda-forge/eccodes-feedstock/builds/21779011#L105). That hasn't been there before.

**Comment by dtip** [comment]
Fairly sure the problem is that libarchive is refusing to extract the symlinks in the source code on Windows. I'm looking for a flag of some sort to pass to it, similar to the `--config core-symlinks=true` we were using to git clone the repo on Windows before commit d7d43b86abcd050727ec93bdc1a15ecdd6260ca7

**Comment by dtip** [comment]
It's definitely a known issue: https://github.com/conda-forge/conda-smithy/issues/1002 https://github.com/conda/conda-build/issues/3351

**Comment by dtip** [comment]
Looks like commit https://github.com/conda-forge/eccodes-feedstock/pull/60/commits/d04a6c81af95d27fa780ff888fcddfd9352f5813 fixed the symlink extraction problem but it's far from ideal: it involves a manual change to an auto-generated file.

Given this problem is an active issue in conda-build at the moment we might be okay to use this commit as a temporary workaround until the issue is fixed.

**Pull request merged**
