### PR TITLE
Version 2.2.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf Quick question, the travis log size gets over 4M and the build fails for this reason. Can I apply this here (https://github.com/conda-forge/pyferret-feedstock/pull/13/commits/7daf83d6bc7e31fc8c52cf7863a15e9ff33e77d4).

**Comment by ocefpaf** [comment]
> @ocefpaf Quick question, the travis log size gets over 4M and the build fails for this reason. Can I apply this here (https://github.com/conda-forge/pyferret-feedstock/pull/13/commits/7daf83d6bc7e31fc8c52cf7863a15e9ff33e77d4).

Yep. I use that with `pyferret` and `gdal` and it works like a charm. (I lost the Stackoverflow link for the discussion but it should not be hard to find it again.)

**Comment by kmuehlbauer** [comment]
@ocefpaf Now I get "The job exceeded the maximum time limit for jobs, and has been terminated." (Ran for 48 min 3 sec). 

Does travis also run with two cores?

**Comment by ocefpaf** [comment]
> Does travis also run with two cores?

Yep. You can use `CPU_COUNT` to access that. See https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/63/files

**Comment by kmuehlbauer** [comment]
@ocefpaf The travis run is [almost done](https://travis-ci.org/conda-forge/eccodes-feedstock/builds/220947151#L1615) when the time limit hits. I've no idea how to proceed. Perhaps skipping some tests?

**Comment by ocefpaf** [comment]
> Perhaps skipping some tests?

Sadly yes :unamused: 

We hope to change that situation soon. See https://github.com/conda-forge/conda-forge.github.io/issues/306

**Pull request merged**
