### PR TITLE
Update boost pinning to 1.62.*

### PR DESCRIPTION
**Pull request by jjhelmus**
`conda-forge` is using a default pinning of boost to 1.62.*.  This update the recipe to use this version.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@jjhelmus Ach, that's why the python-eccodes doesn't build?

**Comment by jjhelmus** [comment]
> that's why the python-eccodes doesn't build?

Yes, I believe so.

**Comment by kmuehlbauer** [comment]
@jjhelmus Thanks for fixing.

**Comment by kynan** [comment]
ecCodes doesn't actually need boost to run. I think we could remove it from run and only leave it as a build dependency.

**Comment by kmuehlbauer** [comment]
@kynan So `boost` is just needed for the testing framework? Since we test only when building, we can try to remove it from as a run dependency. 

Then, we should do this also for `python-eccodes`. BTW, do you happen to know, if this also applies to `perl`? AFAIK `perl` is only used for comparing files while testing.

**Comment by kynan** [comment]
Yes, I believe that is true. I'll make that change for `python-eccodes` first.

**Pull request merged**
