### PR TITLE
Use OpenJPEG only on Windows

### PR DESCRIPTION
**Pull request by dtip**
Following on from https://github.com/conda-forge/eccodes-feedstock/pull/92

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@dtip Not sure, but might it work to just set `OPENJPEG_INCLUDE_DIR` properly for the linux/macosx builds to get openjpeg running?

**Comment by kmuehlbauer** [comment]
> @dtip Not sure, but might it work to just set `OPENJPEG_INCLUDE_DIR` properly for the linux/macosx builds to get openjpeg running?

@dopplershift did set this variable in the `bld.bat`. But we missed to set it in the `build.sh`.

**Comment by dtip** [comment]
@kmuehlbauer you're probably right. Done it this way because it's quick and easy ;)

Is there any preference from users about Jasper vs OpenJPEG? I have to admit I don't know the pros & cons of the two.

**Comment by dtip** [comment]
Linux:
```
-- The following OPTIONAL packages have been found:
...
 * JPEG
 * Jasper
...
```

Windows:
```
-- The following OPTIONAL packages have been found:
...
 * JPEG
 * OpenJPEG
...
```

I think this should fix the problem.

**Comment by kmuehlbauer** [comment]
> Is there any preference from users about Jasper vs OpenJPEG? I have to admit I don't know the pros & cons of the two.

OpenJPEG should perform better than JasPer according to [some benchmarking](https://www.fastcompression.com/benchmarks/benchmarks-j2k.htm). 

Does ECMWF have some experiences regarding usage of these libraries? @StephanSiemen

**Comment by dtip** [comment]
@trexfeathers this should fix the issue you were seeing

**Comment by trexfeathers** [comment]
> @trexfeathers this should fix the issue you were seeing

Fixed! Thanks for the quick response

**Comment by kmuehlbauer** [comment]
@dtip @trexfeathers FYI: The packages without JPEG support have been moved to `broken` label.

**Pull request merged**
