### PR TITLE
Update bld.bat

### PR DESCRIPTION
**Pull request by shahramn**
Add thread-safety. See https://confluence.ecmwf.int/display/UDOC/Is+ecCodes+thread-safe+-+ecCodes+FAQ

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by StephanSiemen** [comment]
@shahramn,

your change triggers errors on Windows:
`Scanning dependencies of target eccodes.pc-pkg-config
[  0%] Built target eccodes.pc-pkg-config
Scanning dependencies of target eccodes
[  0%] Building C object src/CMakeFiles/eccodes.dir/grib_api_version.c.obj
grib_api_version.c
%SRC_DIR%\src\grib_api_internal.h(125): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.`

**Comment by kmuehlbauer** [comment]
@shahramn @StephanSiemen We might need to add `- pthreads-win32  # [win]` to host and run section.

**Comment by kmuehlbauer** [comment]
It compiles but throws a linker error now. Maybe we need another pthread-stubs package?

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
Seems like the linker doesn't like the `-lpthreads` /  `/lpthreads`. A problem with cmake?

**Comment by kmuehlbauer** [comment]
@dtip While you are around, could you have a look at the windows build here?

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
After adding `pthreads-win32` to the windows build threading is found in cmake but linking doesn't 'work
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=223668&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1682

```[ 63%] Linking C shared library ..\bin\eccodes.dll
LINK: command "C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\eccodes.dir\objects1.rsp /out:..\bin\eccodes.dll /implib:..\lib\eccodes.lib /pdb:%SRC_DIR%\build\bin\eccodes.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO /DEF:CMakeFiles\eccodes.dir\exports.def %PREFIX%\Library\lib\libpng.lib %PREFIX%\Library\lib\z.lib %PREFIX%\Library\lib\openjp2.lib -lpthreads kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:..\bin\eccodes.dll.manifest" failed (exit code 1120) with the following output:
LINK : warning LNK4044: unrecognized option '/lpthreads'; ignored
   Creating library ..\lib\eccodes.lib and object ..\lib\eccodes.exp

```
It seems that cmake is adding `-lpthreads` instead of the windows equivalent to the linker commandline.

ping @shahramn @StephanSiemen Looks like a problem in the eccodes cmake machinery, any thoughts?

**Pull request closed without merging**
