### PR TITLE
Pin to libnetcdf 4.4

### PR DESCRIPTION
**Pull request by ocefpaf**
Let's wait for https://github.com/conda-forge/libnetcdf-feedstock/pull/1 to be merged first before merging this one.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
There are some issues with libnetcdf and hdf5:

package                    |            build

    ---------------------------|-----------------

    ca-certificates-2016.2.28  |                0         157 KB  conda-forge

    cmake-3.5.0                |                3        13.5 MB  conda-forge

    icu-56.1                   |                2        22.0 MB  conda-forge

    jpeg-9b                    |                0         243 KB  conda-forge

    sqlite-3.13.0              |                0         1.4 MB  defaults

    tk-8.5.19                  |                0         2.0 MB  conda-forge

    zlib-1.2.8                 |                3          90 KB  conda-forge

    hdf5-1.8.16                |                3         2.9 MB  conda-forge

    jasper-1.900.1             |                2         299 KB  conda-forge

    libpng-1.6.21              |                1         287 KB  conda-forge

    openssl-1.0.2h             |                0         3.2 MB  conda-forge

    curl-7.45.0                |                0         371 KB  defaults

    python-3.5.0               |                1        12.7 MB  defaults

    boost-1.60.0               |           py35_3        13.1 MB  conda-forge

    libnetcdf-4.4.0            |                1         980 KB  defaults

    setuptools-21.2.1          |           py35_0         460 KB  defaults

    ------------------------------------------------------------

For run, these packages are pulled:

package                    |            build

    ---------------------------|-----------------

    hdf4-4.2.11                |                3         906 KB  conda-forge

    hdf5-1.8.15.1              |                2         1.6 MB  defaults

    curl-7.49.0                |                0         494 KB  defaults

    libnetcdf-4.4.0            |                0         1.5 MB  conda-forge

    eccodes-0.13.0             |                2         3.6 MB  file:///Users/travis/miniconda3/conda-bld/osx-64/

    ------------------------------------------------------------

At least libnetcdf and hdf5 versions for build and run are different here. Can someone shed some light, why `conda` pulls different versions for build and run? ping @jakirkham @msarahan @ocefpaf

**Comment by ocefpaf** [comment]
@kmuehlbauer hopefully those failures will be fixed on we merge https://github.com/conda-forge/libnetcdf-feedstock/pull/1

**Comment by kmuehlbauer** [comment]
@ocefpaf I wonder if the failing test on circleCI is related to the missing `perl` issue. I looked at the sources and in this particular test a perl script is used to compare two files. Just for the sake of knowing, could you add perl as build dependency?

**Comment by ocefpaf** [comment]
> @ocefpaf I wonder if the failing test on circleCI is related to the missing `perl` issue. I looked at the sources and in this particular test a perl script is used to compare two files. Just for the sake of knowing, could you add perl as build dependency?

Probably. Let's see if adding `perl` fixes this.

**Pull request merged**
